### PR TITLE
Several fixes for building on Linux

### PR DESCRIPTION
**Pull request by cyberjunky**
With these fixes I got ttwatcher to build on Linux (Ubuntu 14.04, Qt 5.2.1)

### CODE REVIEW

**Comment by altera2015** [comment]
Hey Ron, I've cherry picked around the lightmaps.\* deletion. Thanks for the fixes!

**Comment by cyberjunky** [comment]
Yes that was a mistake. I'm now looking into the Linux hid not working... Hid_enumerate with 0 as second argument for all deviceids has a bug.. Great project anyway...

**Comment by altera2015** [comment]
Does it work with the PID hard-coded? Looks like TT is only using one PID for all watches. Might be easier fix.

**Comment by cyberjunky** [comment]
Correct, it reports the device then in my qdebug output but still doesn't show up in GUI.. Another issue I think, will test tomorrow... We will fix this..

**Pull request closed without merging**
